samplerpresets.push({
    "preset": "Esolithe - Balanced",
    "description": "Eso's tweaked settings - Balanced",
    "temp": 0.8,
    "rep_pen": 1.05,
    "top_p": 1,
    "top_k": 100,
    "top_a": 0,
    "typical": 1,
    "tfs": 1,
    "min_p": 0.02,
    "presence_penalty": 0.02,
    "sampler_seed": -1,
    "rep_pen_range": 512,
    "rep_pen_slope": 0.7,
    "smoothing_factor": 0,
    "smoothing_curve": 0.1,
    "sampler_order": [
        6,
        0,
        1,
        3,
        4,
        2,
        5
    ],
    "nsigma": 0.75,
    "dry_multiplier": 0,
    "dry_base": 1.75,
    "dry_allowed_length": 2,
    "dry_penalty_last_n": 320,
    "dry_sequence_breakers": [
        "\n",
        ": ",
        "\"",
        "*"
    ],
    "xtc_threshold": 0.2,
    "xtc_probability": 0,
    "adaptivep_target": 0.5,
    "adaptivep_decay": 0.9,
    "miro_type": 0,
    "miro_tau": 5,
    "miro_eta": 0.1,
    "grammar": "",
    "dynatemp_range": 0,
    "dynatemp_exponent": 1,
    "second_ep_qty": "0",
    "second_ep_model": "undefined",
    "second_ep_url": "undefined"
})

