window.themes = {
    "Default (Cedo)": {
        "--theme_color_topmenu": "#32496d",
        "--theme_color_topbtn": "#415577",
        "--theme_color_bg_outer": "#182330",
        "--theme_color_bg_chat": "#0b141a",
        "--theme_color_bg_popups": "#182330",
        "--theme_color_bg_muted": "#484d56",
        "--theme_color_accent_bg": "#32496d",
        "--theme_color_accent_bg_highlight": "#596985",
        "--theme_color_accent_fg": "#d1d1d1",
        "--theme_color_accent_fg_highlight": "#d1d1d1",
        "--theme_color_fg": "#d1d1d1",
        "--theme_color_fg_highlight": "#94d7ff",
        "--theme_color_fg_muted": "#9b9b9b",
        "--theme_color_input_bg": "#475162",
        "--theme_color_input_fg": "#e0e0e0",
        "--theme_color_border": "#415577",
        "--theme_color_border_highlight": "#324a6c",
        "--theme_color_user_name": "#18d4bb",
        "--theme_color_ai_name": "#da6060",
        "--theme_color_user_msg_bg": "#005c4b",
        "--theme_color_user_msg_fg": "#e1e6e7",
        "--theme_color_ai_msg_bg": "#1d282f",
        "--theme_color_ai_msg_fg": "#e1e6e7",
        "--theme_color_pending_text": " #f1dd21",
    },
    "Nostalgia (Cedo)": {
        "--theme_color_topmenu": "#337ab7",
        "--theme_color_topbtn": "#4787be",
        "--theme_color_bg_outer": "#303030",
        "--theme_color_bg_muted": "#7e7e7e",
        "--theme_color_bg_chat": "#262626",
        "--theme_color_bg_popups": "#263040",
        "--theme_color_accent_bg": "#337ab7",
        "--theme_color_accent_bg_highlight": "#286090",
        "--theme_color_accent_fg": "#d1d1d1",
        "--theme_color_accent_fg_highlight": "#d1d1d1",
        "--theme_color_fg": "#d1d1d1",
        "--theme_color_fg_highlight": "#76afff",
        "--theme_color_fg_muted": "#9b9b9b",
        "--theme_color_input_bg": "#474747",
        "--theme_color_input_fg": "#e0e0e0",
        "--theme_color_border": "#76afff",
        "--theme_color_border_highlight": "#76afff",
        "--theme_color_user_name": "#18d4bb",
        "--theme_color_ai_name": "#da6060",
        "--theme_color_user_msg_bg": "#005c4b",
        "--theme_color_user_msg_fg": "#e1e6e7",
        "--theme_color_ai_msg_bg": "#1d282f",
        "--theme_color_ai_msg_fg": "#e1e6e7",
        "--theme_color_pending_text": " #f1dd21",
    },
    "Tako (Lakius)": {
        "--theme_color_topmenu": "#2a1f33",
        "--theme_color_topbtn": "#c88333",
        "--theme_color_bg_outer": "#170f1a",
        "--theme_color_bg_muted": "#484d56",
        "--theme_color_bg_chat": "#211b22",
        "--theme_color_bg_popups": "#2f2231",
        "--theme_color_accent_bg": "#a6722f",
        "--theme_color_accent_bg_highlight": "#dc901c",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "#ffffff",
        "--theme_color_fg_muted": "#9b9b9b",
        "--theme_color_fg_highlight": "#e68e3a",
        "--theme_color_input_bg": "#5c3b6b",
        "--theme_color_input_fg": "#e0e0e0",
        "--theme_color_border": "#bd8857",
        "--theme_color_border_highlight": "#e68e3a",
        "--theme_color_user_name": "#ffffff",
        "--theme_color_ai_name": "#cacaca",
        "--theme_color_user_msg_bg": "#272727",
        "--theme_color_user_msg_fg": "#e6e6e6",
        "--theme_color_ai_msg_bg": "#191919",
        "--theme_color_ai_msg_fg": "#bcbcbc",
        "--theme_color_pending_text": " #f1af21",
    },
    "Shadow (TwistedShadows)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#000000",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#000000",
        "--theme_color_accent_bg": "#2c2c2c",
        "--theme_color_accent_bg_highlight": "#4d4d4d",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#ffffff",
        "--theme_color_fg_highlight": "#ffffff",
        "--theme_color_fg_muted": "#9b9b9b",
        "--theme_color_input_bg": "#2c2c2c",
        "--theme_color_input_fg": "#ffffff",
        "--theme_color_border": "#1a1a1a",
        "--theme_color_border_highlight": "#000000",
        "--theme_color_user_name": "#ffffff",
        "--theme_color_ai_name": "#cacaca",
        "--theme_color_user_msg_bg": "#272727",
        "--theme_color_user_msg_fg": "#e6e6e6",
        "--theme_color_ai_msg_bg": "#191919",
        "--theme_color_ai_msg_fg": "#bcbcbc",
        "--theme_color_pending_text": " #f1dd21",
    },
    "Candy (Peter)": {
        "--theme_color_topmenu": "#ff69b4b3",
        "--theme_color_topbtn": "#ff69b4b3",
        "--theme_color_bg_outer": "#182330",
        "--theme_color_bg_muted": "#484d56",
        "--theme_color_bg_chat": "#0b141a",
        "--theme_color_bg_popups": "#182330",
        "--theme_color_accent_bg": "#ff69b499",
        "--theme_color_accent_bg_highlight": "#00bfffcc",
        "--theme_color_accent_fg": "#d1d1d1",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#d1d1d1",
        "--theme_color_fg_muted": "#9e9e9e",
        "--theme_color_fg_highlight": "#82a1bc",
        "--theme_color_input_bg": "#475162",
        "--theme_color_input_fg": "#e0e0e0",
        "--theme_color_border": "#ff69b4",
        "--theme_color_border_highlight": "#82a1bc",
        "--theme_color_pending_text": " #e68ecc",
    },
    "Aqua (Dr. Toaster)": {
        "--theme_color_topmenu": "#002b36",
        "--theme_color_topbtn": "#244752",
        "--theme_color_bg_outer": "#647476",
        "--theme_color_bg_muted": "#484d56",
        "--theme_color_bg_chat": "#244752ad",
        "--theme_color_bg_popups": "#244752",
        "--theme_color_accent_bg": "#002b36",
        "--theme_color_accent_bg_highlight": "#4b7b8a",
        "--theme_color_accent_fg": "#a0bebe",
        "--theme_color_accent_fg_highlight": "#a0bebe",
        "--theme_color_fg": "#a0bebe",
        "--theme_color_fg_highlight": "#82a1bc",
        "--theme_color_fg_muted": "#aaaaaa",
        "--theme_color_input_bg": "#244752",
        "--theme_color_input_fg": "#a0bebe",
        "--theme_color_border": "#7c8e8e",
        "--theme_color_border_highlight": "#82a1bc",
        "--theme_color_pending_text": " #90f7fa",
    },
    "OLED: Kobold Blue (Rose22)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#1c354a",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#030303",
        "--theme_color_accent_bg": "#0d1821",
        "--theme_color_accent_bg_highlight": "#143148",
        "--theme_color_accent_fg": "#cde8ff",
        "--theme_color_accent_fg_highlight": "#cde8ff",
        "--theme_color_fg": "#cde8ff",
        "--theme_color_fg_highlight": "#4db6eb",
        "--theme_color_fg_muted": "#91a4b4",
        "--theme_color_input_bg": "#0d1821",
        "--theme_color_input_fg": "#b5e3ff",
        "--theme_color_border": "#44a0ce",
        "--theme_color_border_highlight": "#4db6eb",
        "--theme_color_user_name": "#86F9F7",
        "--theme_color_ai_name": "#5899B1",
        "--theme_color_user_msg_bg": "#112636",
        "--theme_color_user_msg_fg": "#B2CEE5",
        "--theme_color_ai_msg_bg": "#0b1a24",
        "--theme_color_ai_msg_fg": "#AFC3D5",
        "--theme_color_pending_text": "#69dfff",
    },
    "OLED: Cherry Pink (Rose22)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#2b0419",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#030303",
        "--theme_color_accent_bg": "#1d0311",
        "--theme_color_accent_bg_highlight": "#270417",
        "--theme_color_accent_fg": "#ffa8e2",
        "--theme_color_accent_fg_highlight": "#ffa8e2",
        "--theme_color_fg": "#ffa8e2",
        "--theme_color_fg_highlight": "#e961ac",
        "--theme_color_fg_muted": "#792151",
        "--theme_color_input_bg": "#18020f",
        "--theme_color_input_fg": "#ffa8e2",
        "--theme_color_border": "#ba0f6c",
        "--theme_color_border_highlight": "#f41991",
        "--theme_color_user_name": "#E19CBF",
        "--theme_color_ai_name": "#f41991",
        "--theme_color_user_msg_bg": "#29041A",
        "--theme_color_user_msg_fg": "#ffa8e2",
        "--theme_color_ai_msg_bg": "#18010F",
        "--theme_color_ai_msg_fg": "#ffa8e2",
        "--theme_color_pending_text": "#ffa8e2",
    },
    "OLED: Matrix Green (Rose22)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#001600",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#030303",
        "--theme_color_accent_bg": "#000000",
        "--theme_color_accent_bg_highlight": "#001600",
        "--theme_color_accent_fg": "#26E840",
        "--theme_color_accent_fg_highlight": "#26E840",
        "--theme_color_fg": "#26e840",
        "--theme_color_fg_highlight": "#00bc2c",
        "--theme_color_fg_muted": "#004d09",
        "--theme_color_input_bg": "#001600",
        "--theme_color_input_fg": "#00FF41",
        "--theme_color_border": "#008F11",
        "--theme_color_border_highlight": "#00bc2c",
        "--theme_color_user_name": "#00FF41",
        "--theme_color_ai_name": "#00bc2c",
        "--theme_color_user_msg_bg": "#002f05",
        "--theme_color_user_msg_fg": "#26E840",
        "--theme_color_ai_msg_bg": "#001802",
        "--theme_color_ai_msg_fg": "#26E840",
        "--theme_color_pending_text": "#00FF41",
    },
    "OLED: Mystic Purple (Rose22)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#35244855",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#030303",
        "--theme_color_accent_bg": "#1a1226",
        "--theme_color_accent_bg_highlight": "#221730",
        "--theme_color_accent_fg": "#ab73e7",
        "--theme_color_accent_fg_highlight": "#ab73e7",
        "--theme_color_fg": "#ab73e7",
        "--theme_color_fg_highlight": "#9b5fdc",
        "--theme_color_fg_muted": "#3d2953",
        "--theme_color_input_bg": "#191124",
        "--theme_color_input_fg": "#bb7fff",
        "--theme_color_border": "#ab73e7",
        "--theme_color_border_highlight": "#ab73e7",
        "--theme_color_user_name": "#bb7fff",
        "--theme_color_ai_name": "#a06dda",
        "--theme_color_user_msg_bg": "#2a1d3d",
        "--theme_color_user_msg_fg": "#bb7fff",
        "--theme_color_ai_msg_bg": "#1a1226",
        "--theme_color_ai_msg_fg": "#ab73e7",
        "--theme_color_pending_text": "#bb7fff",
    },
    "OLED: Monochrome (Rose22)": {
        "--theme_color_topmenu": "#000000",
        "--theme_color_topbtn": "#35353599",
        "--theme_color_bg_outer": "#000000",
        "--theme_color_bg_muted": "#000000",
        "--theme_color_bg_chat": "#000000",
        "--theme_color_bg_popups": "#030303",
        "--theme_color_accent_bg": "#171717",
        "--theme_color_accent_bg_highlight": "#1e1e1e",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#ffffff",
        "--theme_color_fg_muted": "#bcbcbc",
        "--theme_color_fg_highlight": "#cacaca",
        "--theme_color_input_bg": "#191919",
        "--theme_color_input_fg": "#e6e6e6",
        "--theme_color_border": "#d4d4d4",
        "--theme_color_border_highlight": "#cacaca",
        "--theme_color_user_name": "#ffffff",
        "--theme_color_ai_name": "#cacaca",
        "--theme_color_user_msg_bg": "#272727",
        "--theme_color_user_msg_fg": "#e6e6e6",
        "--theme_color_ai_msg_bg": "#191919",
        "--theme_color_ai_msg_fg": "#bcbcbc",
        "--theme_color_pending_text": "#bcbcbc",
    },
    "Dark (based on llama.cpp UI) (Rose22)": {
        "--theme_color_topmenu": "#171717",
        "--theme_color_topbtn": "#232323",
        "--theme_color_bg_outer": "#0d0d0d",
        "--theme_color_bg_muted": "#171717",
        "--theme_color_bg_chat": "#0d0d0d",
        "--theme_color_bg_popups": "#0d0d0d",
        "--theme_color_accent_bg": "#232323",
        "--theme_color_accent_bg_highlight": "#2f2f2f",
        "--theme_color_accent_fg": "#fafafa",
        "--theme_color_accent_fg_highlight": "#fafafa",
        "--theme_color_fg": "#fafafa",
        "--theme_color_fg_muted": "#a1a1a1",
        "--theme_color_fg_highlight": "#fafafa",
        "--theme_color_input_bg": "#2A2A2A",
        "--theme_color_input_fg": "#fafafa",
        "--theme_color_border": "#232323",
        "--theme_color_border_highlight": "#232323",
        "--theme_color_user_name": "#171717",
        "--theme_color_ai_name": "#fafafa",
        "--theme_color_user_msg_bg": "#E5E5E5",
        "--theme_color_user_msg_fg": "#171717",
        "--theme_color_ai_msg_bg": "#0D0D0D",
        "--theme_color_ai_msg_fg": "#fafafa",
        "--theme_color_pending_text": " #a1a1a1",
    },
    "Light (based on ChatGPT) (Rose22)": {
        "--theme_color_topmenu": "#F9F9F9",
        "--theme_color_topbtn": "#FFFFFF",
        "--theme_color_bg_outer": "#FFFFFF",
        "--theme_color_bg_muted": "#b6b6b6",
        "--theme_color_bg_chat": "#FFFFFF",
        "--theme_color_bg_popups": "#FFFFFF",
        "--theme_color_accent_bg": "#FFFFFF",
        "--theme_color_accent_bg_highlight": "#EAEAEA",
        "--theme_color_accent_fg": "#444444",
        "--theme_color_accent_fg_highlight": "#444444",
        "--theme_color_fg": "#0D0D0D",
        "--theme_color_fg_muted": "#8F8F8F",
        "--theme_color_fg_highlight": "#0D0D0D",
        "--theme_color_input_bg": "#FFFFFF",
        "--theme_color_input_fg": "#0D0D0D",
        "--theme_color_border": "#EDEDED",
        "--theme_color_border_highlight": "#EDEDED",
        "--theme_color_user_name": "#0D0D0D",
        "--theme_color_ai_name": "#0D0D0D",
        "--theme_color_user_msg_bg": "#F4F4F4",
        "--theme_color_user_msg_fg": "#0D0D0D",
        "--theme_color_ai_msg_bg": "#FFFFFF",
        "--theme_color_ai_msg_fg": "#0D0D0D",
        "--theme_color_pending_text": "#8F8F8F",
    },
    "Discord (Rose22)": {
        "--theme_color_topmenu": "#121214",
        "--theme_color_topbtn": "#222327",
        "--theme_color_bg_outer": "#121214",
        "--theme_color_bg_muted": "#131315",
        "--theme_color_bg_chat": "#1A1A1E",
        "--theme_color_bg_popups": "#1A1A1E",
        "--theme_color_accent_bg": "#222327",
        "--theme_color_accent_bg_highlight": "#25262a",
        "--theme_color_accent_fg": "#E8E8E8",
        "--theme_color_accent_fg_highlight": "#E8E8E8",
        "--theme_color_fg": "#E3E3E5",
        "--theme_color_fg_muted": "#5A5B63",
        "--theme_color_fg_highlight": "#E3E3E5",
        "--theme_color_input_bg": "#222327",
        "--theme_color_input_fg": "#e0e0e0",
        "--theme_color_border": "#232328",
        "--theme_color_border_highlight": "#232323",
        "--theme_color_user_name": "#E3E3E5",
        "--theme_color_ai_name": "#E3E3E5",
        "--theme_color_user_msg_bg": "#242428",
        "--theme_color_user_msg_fg": "#E3E3E5",
        "--theme_color_ai_msg_bg": "#1A1A1E",
        "--theme_color_ai_msg_fg": "#E3E3E5",
        "--theme_color_pending_text": "#131315",
    },
    "Catppuccin Mocha (Rose22)": {
        "--theme_color_topmenu": "#313244",
        "--theme_color_topbtn": "#45475a",
        "--theme_color_bg_outer": "#11111b",
        "--theme_color_bg_muted": "#181825",
        "--theme_color_bg_chat": "#181825",
        "--theme_color_bg_popups": "#1e1e2e",
        "--theme_color_accent_bg": "#45475a",
        "--theme_color_accent_bg_highlight": "#585b70",
        "--theme_color_accent_fg": "#cdd6f4",
        "--theme_color_accent_fg_highlight": "#cdd6f4",
        "--theme_color_fg": "#cdd6f4",
        "--theme_color_fg_muted": "#6c7086",
        "--theme_color_fg_highlight": "#bac2de",
        "--theme_color_input_bg": "#45475a",
        "--theme_color_input_fg": "#cdd6f4",
        "--theme_color_border": "#45475a",
        "--theme_color_border_highlight": "#45475a",
        "--theme_color_user_name": "#bac2de",
        "--theme_color_ai_name": "#a6adc8",
        "--theme_color_user_msg_bg": "#45475a",
        "--theme_color_user_msg_fg": "#cdd6f4",
        "--theme_color_ai_msg_bg": "#313244",
        "--theme_color_ai_msg_fg": "#cdd6f4",
        "--theme_color_pending_text": "#6c7086",
    },
    "Light Dark Blue (Peter)": {
        "--theme_color_topmenu": "rgba(255,255,255,1)",
        "--theme_color_topbtn": "rgba(234,241,251,1)",
        "--theme_color_bg_outer": "rgba(243,246,251,1)",
        "--theme_color_bg_chat": "rgba(247,249,252,1)",
        "--theme_color_bg_popups": "rgba(255,255,255,1)",
        "--theme_color_bg_muted": "rgba(239,241,245,1)",
        "--theme_color_accent_bg": "rgba(37,99,235,1)",
        "--theme_color_accent_bg_highlight": "rgba(252,229,136,1)",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "rgba(31,41,55,1)",
        "--theme_color_fg_highlight": "rgba(14,165,165,1)",
        "--theme_color_fg_muted": "#9CA3AF",
        "--theme_color_input_bg": "rgba(255,255,255,1)",
        "--theme_color_input_fg": "#111827",
        "--theme_color_border": "#D1D9E6",
        "--theme_color_border_highlight": "rgba(122,167,255,1)"
    },
    "Light Lite Blue (Peter)": {
        "--theme_color_topmenu": "#FFFFFF",
        "--theme_color_topbtn": "#EDF4FF",
        "--theme_color_bg_outer": "#F3F6FA",
        "--theme_color_bg_chat": "#F7F9FB",
        "--theme_color_bg_popups": "#FFFFFF",
        "--theme_color_bg_muted": "#EEF1F6",
        "--theme_color_accent_bg": "#007ACC",
        "--theme_color_accent_bg_highlight": "#FFE599",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "#1F2937",
        "--theme_color_fg_highlight": "#0EA5A5",
        "--theme_color_fg_muted": "#9CA3AF",
        "--theme_color_input_bg": "#FFFFFF",
        "--theme_color_input_fg": "#111827",
        "--theme_color_border": "#E1E6EF",
        "--theme_color_border_highlight": "#007ACC"
    },
    "Light Lavender (Peter)": {
        "--theme_color_topmenu": "#FAF7FF",
        "--theme_color_topbtn": "#EFE9FF",
        "--theme_color_bg_outer": "#F5F0FF",
        "--theme_color_bg_chat": "#F8F4FF",
        "--theme_color_bg_popups": "#FAF7FF",
        "--theme_color_bg_muted": "#F2EDFA",
        "--theme_color_accent_bg": "#6D5BD0",
        "--theme_color_accent_bg_highlight": "#FDE68A",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "#2E2640",
        "--theme_color_fg_highlight": "#7C3AED",
        "--theme_color_fg_muted": "#9E8FBF",
        "--theme_color_input_bg": "#FFFFFF",
        "--theme_color_input_fg": "#2E2640",
        "--theme_color_border": "#E3DDF3",
        "--theme_color_border_highlight": "#6D5BD0"
    },
    "Light Sand (Peter)": {
        "--theme_color_topmenu": "#FBF7F0",
        "--theme_color_topbtn": "#F1E7D7",
        "--theme_color_bg_outer": "#F1E9DD",
        "--theme_color_bg_chat": "#F4EFE6",
        "--theme_color_bg_popups": "#FBF7F0",
        "--theme_color_bg_muted": "#EDE4D6",
        "--theme_color_accent_bg": "#C37D2F",
        "--theme_color_accent_bg_highlight": "#FFE8B0",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "#3F3A28",
        "--theme_color_fg_highlight": "#0B8B6C",
        "--theme_color_fg_muted": "#9B9079",
        "--theme_color_input_bg": "#FFFFFF",
        "--theme_color_input_fg": "#2F2A1D",
        "--theme_color_border": "#E2D8C8",
        "--theme_color_border_highlight": "#C08A2E"
    },
    "Light Coffee Cream (Peter)": {
        "--theme_color_topmenu": "#FAF4EA",
        "--theme_color_topbtn": "#EFE5D3",
        "--theme_color_bg_outer": "#EFE2C9",
        "--theme_color_bg_chat": "#F2EAD9",
        "--theme_color_bg_popups": "#F7F2E7",
        "--theme_color_bg_muted": "#ECE2D3",
        "--theme_color_accent_bg": "#C9A566",
        "--theme_color_accent_bg_highlight": "#FFE3A3",
        "--theme_color_accent_fg": "#FFFFFF",
        "--theme_color_accent_fg_highlight": "#FFFFFF",
        "--theme_color_fg": "#3B3A36",
        "--theme_color_fg_highlight": "#0E7C86",
        "--theme_color_fg_muted": "#9C907D",
        "--theme_color_input_bg": "#FFFFFF",
        "--theme_color_input_fg": "#2F2E2B",
        "--theme_color_border": "#E4D9C7",
        "--theme_color_border_highlight": "#BFA06A"
    },
    "Mostly black (Peter)": {
        "--theme_color_topmenu": "#151417",
        "--theme_color_topbtn": "#1e1a22",
        "--theme_color_bg_outer": "#101012",
        "--theme_color_bg_chat": "#0e0e10",
        "--theme_color_bg_popups": "#151617",
        "--theme_color_bg_muted": "#1c1c1f",
        "--theme_color_accent_bg": "#7c3aed",
        "--theme_color_accent_bg_highlight": "#3b1f4c",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e5e7eb",
        "--theme_color_fg_highlight": "#7dd46c",
        "--theme_color_fg_muted": "#8a8f98",
        "--theme_color_input_bg": "#121217",
        "--theme_color_input_fg": "#eaedf2",
        "--theme_color_border": "#2a2a2d",
        "--theme_color_border_highlight": "#7c3aed"
    },
    "Dark navy (Peter)": {
        "--theme_color_topmenu": "#0b1a32",
        "--theme_color_topbtn": "#0d223d",
        "--theme_color_bg_outer": "#0a1e3c",
        "--theme_color_bg_chat": "#0a2046",
        "--theme_color_bg_popups": "#0f274f",
        "--theme_color_bg_muted": "#12203b",
        "--theme_color_accent_bg": "#1d4ed8",
        "--theme_color_accent_bg_highlight": "#1f3b6e",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e5ecf6",
        "--theme_color_fg_highlight": "#22d3ee",
        "--theme_color_fg_muted": "#8da3c4",
        "--theme_color_input_bg": "#0f1e3a",
        "--theme_color_input_fg": "#e6eef9",
        "--theme_color_border": "#23314a",
        "--theme_color_border_highlight": "#3b82f6"
    },
    "Ink blue (Peter)": {
        "--theme_color_topmenu": "#0b141e",
        "--theme_color_topbtn": "#0b1622",
        "--theme_color_bg_outer": "#0a121b",
        "--theme_color_bg_chat": "#050c18",
        "--theme_color_bg_popups": "#0d141e",
        "--theme_color_bg_muted": "#111927",
        "--theme_color_accent_bg": "#0284c7",
        "--theme_color_accent_bg_highlight": "#16324a",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e6eef9",
        "--theme_color_fg_highlight": "#67e8f9",
        "--theme_color_fg_muted": "#8ea2b8",
        "--theme_color_input_bg": "#0f1824",
        "--theme_color_input_fg": "#e8f0fa",
        "--theme_color_border": "#1f2a3a",
        "--theme_color_border_highlight": "#38bdf8"
    },
    "Dark charcoal (Peter)": {
        "--theme_color_topmenu": "#161616",
        "--theme_color_topbtn": "#1a1a1a",
        "--theme_color_bg_outer": "#121212",
        "--theme_color_bg_chat": "#141414",
        "--theme_color_bg_popups": "#1a1a1a",
        "--theme_color_bg_muted": "#202020",
        "--theme_color_accent_bg": "#5fa36a",
        "--theme_color_accent_bg_highlight": "#244024",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e5e5e5",
        "--theme_color_fg_highlight": "#10b981",
        "--theme_color_fg_muted": "#969696",
        "--theme_color_input_bg": "#1b1b1b",
        "--theme_color_input_fg": "#e7e7e7",
        "--theme_color_border": "#2a2a2a",
        "--theme_color_border_highlight": "#5fa36a"
    },
    "Dark brown (Peter)": {
        "--theme_color_topmenu": "#1f180f",
        "--theme_color_topbtn": "#261e15",
        "--theme_color_bg_outer": "#1a140e",
        "--theme_color_bg_chat": "#1b1510",
        "--theme_color_bg_popups": "#201a13",
        "--theme_color_bg_muted": "#2a2218",
        "--theme_color_accent_bg": "#b7791f",
        "--theme_color_accent_bg_highlight": "#3a2a1b",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#f1e7da",
        "--theme_color_fg_highlight": "#eab308",
        "--theme_color_fg_muted": "#a59078",
        "--theme_color_input_bg": "#221b14",
        "--theme_color_input_fg": "#f3ede4",
        "--theme_color_border": "#3a2c1d",
        "--theme_color_border_highlight": "#d6a354"
    },
    "Dark olive (Peter)": {
        "--theme_color_topmenu": "#1f201b",
        "--theme_color_topbtn": "#26271f",
        "--theme_color_bg_outer": "#1c1d19",
        "--theme_color_bg_chat": "#1a1b17",
        "--theme_color_bg_popups": "#20211c",
        "--theme_color_bg_muted": "#26271f",
        "--theme_color_accent_bg": "#8d9467",
        "--theme_color_accent_bg_highlight": "#3a3c2c",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e8e9d9",
        "--theme_color_fg_highlight": "#93c5aa",
        "--theme_color_fg_muted": "#9a9b87",
        "--theme_color_input_bg": "#23241f",
        "--theme_color_input_fg": "#eaeaDA",
        "--theme_color_border": "#2e2f27",
        "--theme_color_border_highlight": "#9ca37a"
    },
    "Dark gray (Peter)": {
        "--theme_color_topmenu": "#1a1a1a",
        "--theme_color_topbtn": "#1c1c1c",
        "--theme_color_bg_outer": "#121212",
        "--theme_color_bg_chat": "#151515",
        "--theme_color_bg_popups": "#1a1a1a",
        "--theme_color_bg_muted": "#222222",
        "--theme_color_accent_bg": "#3b82f6",
        "--theme_color_accent_bg_highlight": "#1f2937",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e5e7eb",
        "--theme_color_fg_highlight": "#22d3ee",
        "--theme_color_fg_muted": "#9ca3af",
        "--theme_color_input_bg": "#1e1e1e",
        "--theme_color_input_fg": "#eaeaea",
        "--theme_color_border": "#2a2a2a",
        "--theme_color_border_highlight": "#60a5fa"
    },
    "Dark red (Peter)": {
        "--theme_color_topmenu": "#2a090a",
        "--theme_color_topbtn": "#2e0c0d",
        "--theme_color_bg_outer": "#240707",
        "--theme_color_bg_chat": "#1a0405",
        "--theme_color_bg_popups": "#2a090a",
        "--theme_color_bg_muted": "#341012",
        "--theme_color_accent_bg": "#b91c1c",
        "--theme_color_accent_bg_highlight": "#3a1214",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#fceaea",
        "--theme_color_fg_highlight": "#fca5a5",
        "--theme_color_fg_muted": "#c9a1a1",
        "--theme_color_input_bg": "#2e0c0e",
        "--theme_color_input_fg": "#fdebeb",
        "--theme_color_border": "#5b2325",
        "--theme_color_border_highlight": "#f87171"
    },
    "Dark teal (Peter)": {
        "--theme_color_topmenu": "#0a252d",
        "--theme_color_topbtn": "#0c2a33",
        "--theme_color_bg_outer": "#071b21",
        "--theme_color_bg_chat": "#061f27",
        "--theme_color_bg_popups": "#0b232b",
        "--theme_color_bg_muted": "#0e2a33",
        "--theme_color_accent_bg": "#0ea5a5",
        "--theme_color_accent_bg_highlight": "#163a43",
        "--theme_color_accent_fg": "#ffffff",
        "--theme_color_accent_fg_highlight": "#ffffff",
        "--theme_color_fg": "#e6f7fa",
        "--theme_color_fg_highlight": "#22d3ee",
        "--theme_color_fg_muted": "#91b0b7",
        "--theme_color_input_bg": "#0f2a33",
        "--theme_color_input_fg": "#e6f7fa",
        "--theme_color_border": "#12333b",
        "--theme_color_border_highlight": "#06b6d4"
    }
}