name: koboldcpp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cxx-compiler
  - gxx=10
  - pip
  - git
  - ninja
  - make
  - packaging
  - pyinstaller=6.10
  - libcblas
  - ocl-icd-system
  - libvulkan-loader
  - tk=*=xft_*
  - psutil
  - jinja2
  - pip:
    - customtkinter
    - pdfplumber
    - PyMuPdf
    - tqdm
    - chardet
    - openai
    - tiktoken
    - prompt_toolkit
    - msgpack
    - numpy
    - asyncssh
    - pyyaml
    - json-repair
    - aiofiles
    - python-ulid
    - requests
    - flask
    - discord.py
    - python-telegram-bot
    - matrix-nio
    - beautifulsoup4
