name: koboldcpp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cxx-compiler
  - gxx=10
  - pip
  - git
  - ninja
  - make
  - packaging
  - pyinstaller=6.10
  - libcblas
  - ocl-icd-system
  - libvulkan-loader
  - tk=*=xft_*
  - psutil
  - jinja2
  - pip:
    - customtkinter
    - pdfplumber
    - PyMuPdf
    - tqdm
    - chardet
    - tree-sitter
    - tree-sitter-python
    - tree-sitter-javascript
    - tree-sitter-typescript
    - tree-sitter-html
    - tree-sitter-css
    - tree-sitter-cpp
    - tree-sitter-c-sharp
    - tree-sitter-rust
    - tree-sitter-ruby
    - tree-sitter-go
    - tree-sitter-java
    - openai
    - tiktoken
    - prompt_toolkit
    - msgpack
    - numpy
    - asyncssh
    - pyyaml
    - json-repair
    - aiofiles
    - python-ulid
    - requests
    - fastapi
    - uvicorn
    - itsdangerous
    - websockets
    - python-multipart
    - discord.py
    - python-telegram-bot
    - matrix-nio
    - beautifulsoup4
    - ddgs
